Repository InnovaGameCreate/mythos-encounter, pull requests merged in 2024-10, with the labels that each got.

#196 温度計実装
  Assets/Plugins/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/LiberationSans SDF - Metalic Green.mat
  Assets/Plugins/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Assets/Resources/Image/Item/Tehermometer.png
  Assets/Resources/Image/Item/Tehermometer.png.meta
  Assets/Resources/ItemData/Thermometer.asset
  Assets/Resources/ItemData/Thermometer.asset.meta
  Assets/Resources/Prefab/Item/Thermometer.prefab
  Assets/Resources/Prefab/Item/Thermometer.prefab.meta
  Assets/Resources/Prefab/Item/UsingItem.meta
  Assets/Resources/Prefab/Item/UsingItem/Compass.meta
  Assets/Resources/Prefab/Item/UsingItem/Compass/New Material 4.mat
  Assets/Resources/Prefab/Item/UsingItem/Compass/New Material 4.mat.meta
  Assets/Resources/Prefab/Item/UsingItem/Compass/New Material.mat
  Assets/Resources/Prefab/Item/UsingItem/Compass/New Material.mat.meta
  Assets/Resources/Prefab/Item/UsingItem/Compass/UsingCompass.prefab
  Assets/Resources/Prefab/Item/UsingItem/Compass/UsingCompass.prefab.meta
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass.meta
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/CustomUnlit.shader
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/CustomUnlit.shader.meta
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/New Material 1.mat
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/New Material 1.mat.meta
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/New Material 5.mat
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/New Material 5.mat.meta
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/UsingCompass ShaderCustom.prefab
  Assets/Resources/Prefab/Item/UsingItem/ShaderCustomCompass/UsingCompass ShaderCustom.prefab.meta
  Assets/Resources/Prefab/Item/UsingItem/Thermometer.meta
  Assets/Resources/Prefab/Item/UsingItem/Thermometer/UsingThermometer.prefab
  Assets/Resources/Prefab/Item/UsingItem/Thermometer/UsingThermometer.prefab.meta
  Assets/Resources/Prefab/Player.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/Floor_HH_Test.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/Floor_HH_Test.prefab.meta
  Assets/Scenes/InGame_ThermometerTest.unity
  Assets/Scenes/InGame_ThermometerTest.unity.meta
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/CompassEffect.cs
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/ThermometetEffect.cs
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/ThermometetEffect.cs.meta
  Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem.meta
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Compass.meta
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Compass/CompassMove.cs
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Compass/CompassMove.cs.meta
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Thermometer.meta
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Thermometer/ThermometerMove.cs
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Thermometer/ThermometerMove.cs.meta
Labels: 優先度中

#208 ディスプレイUIへのマッチング機能の追加
  Assets/Resources/Prefab/Lobby/obj_Settings_tmp.prefab
  Assets/Resources/Prefab/Lobby/obj_Settings_tmp.prefab.meta
  Assets/Resources/Prefab/PlayerInfo.prefab
  Assets/Resources/Prefab/PlayerInfo.prefab.meta
  Assets/Resources/Prefab/Runner_Tmp_Kobayashi.prefab
  Assets/Resources/Prefab/Runner_Tmp_Kobayashi.prefab.meta
  Assets/Scenes/Lobby_Multi.unity
  Assets/Scenes/Lobby_Multi.unity.meta
  Assets/Scripts/Common/Network.meta
  Assets/Scripts/Common/Network/PlayerInfo.cs
  Assets/Scripts/Common/Network/PlayerInfo.cs.meta
  Assets/Scripts/Common/Network/RunnerManager.cs
  Assets/Scripts/Common/Network/RunnerManager.cs.meta
  Assets/Scripts/HostMigration/Test/InGame.unity
  Assets/Scripts/HostMigration/Test/Player.prefab
  Assets/Scripts/HostMigration/Test/PlayerInfo.cs
  Assets/Scripts/HostMigration/Test/RunnerManager.cs
  Assets/Scripts/HostMigration/Test/Start.unity
  Assets/Scripts/HostMigration/Test/StartManager.cs
  Assets/Scripts/Scenes/Lobby.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/LookDisplayObject.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/LookDisplayObject.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_1.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_1.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_2.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_2.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_3.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_3.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_4.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_4.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_6.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSetting_6.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSettion_5.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/RoomSettion_5.cs.meta
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/UIManager.cs
  Assets/Scripts/Scenes/Lobby/RoomSettingPanel/UIManager.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: 優先度中

#207 SAN値回復薬実装
  Assets/Resources/ItemData/SanityPotion.asset
  Assets/Resources/ItemData/SanityPotion.asset.meta
  Assets/Resources/Prefab/Item/SanityPotion.prefab
  Assets/Resources/Prefab/Item/SanityPotion.prefab.meta
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/SanityPotionEffect.cs
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/SanityPotionEffect.cs.meta
Labels: 優先度中

#210 プレイヤーの情報をPlayerInformationを元に更新できるように修正
  Assets/Scenes/APIDevelop.unity
  Assets/Scripts/Data/APITester.cs
  Assets/Scripts/Data/PlayerInformation.cs
  Assets/Scripts/Data/PlayerInformationFacade.cs
Labels: 優先度高

#202 放射線測定器実装
  Assets/Resources/Image/Item/GeigerCounter.png
  Assets/Resources/Image/Item/GeigerCounter.png.meta
  Assets/Resources/ItemData/GeigerCounter.asset
  Assets/Resources/ItemData/GeigerCounter.asset.meta
  Assets/Resources/Prefab/Item/GeigerCounter.prefab
  Assets/Resources/Prefab/Item/GeigerCounter.prefab.meta
  Assets/Resources/Prefab/Item/UsingItem/Compass/UsingCompass.prefab
  Assets/Resources/Prefab/Item/UsingItem/GeigerCounter.meta
  Assets/Resources/Prefab/Item/UsingItem/GeigerCounter/New Material.mat
  Assets/Resources/Prefab/Item/UsingItem/GeigerCounter/New Material.mat.meta
  Assets/Resources/Prefab/Item/UsingItem/GeigerCounter/UsingGeigerCounter.prefab
  Assets/Resources/Prefab/Item/UsingItem/GeigerCounter/UsingGeigerCounter.prefab.meta
  Assets/Resources/Prefab/Player.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/Floor_HH_Test.prefab
  Assets/Scenes/InGame_ThermometerTest.meta
  Assets/Scenes/InGame_ThermometerTest/Global Volume Profile 1.asset
  Assets/Scenes/InGame_ThermometerTest/Global Volume Profile 1.asset.meta
  Assets/Scenes/InGame_ThermometerTest/Global Volume Profile 2.asset
  Assets/Scenes/InGame_ThermometerTest/Global Volume Profile 2.asset.meta
  Assets/Scenes/InGame_ThermometerTest/Global Volume Profile.asset
  Assets/Scenes/InGame_ThermometerTest/Global Volume Profile.asset.meta
  Assets/Scenes/Testtest.meta
  Assets/Scenes/Testtest.unity
  Assets/Scenes/Testtest.unity.meta
  Assets/Scenes/Testtest/Global Volume Profile.asset
  Assets/Scenes/Testtest/Global Volume Profile.asset.meta
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/GeigerCounterEffect.cs
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/GeigerCounterEffect.cs.meta
  Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/GeigerCounter.meta
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/GeigerCounter/GeigerCounterMove.cs
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/GeigerCounter/GeigerCounterMove.cs.meta
  Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Thermometer/ThermometerMove.cs
  ProjectSettings/TagManager.asset
Labels: 優先度中

#217 デバッグ用のツール開発
  Assets/Editor/DebugMenu.cs
  Assets/Editor/DebugMenu.cs.meta
  Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
Labels: 優先度高

#214 触手のアイテムの追加
  Assets/Resources/ItemData/Tantacle.asset
  Assets/Resources/ItemData/Tantacle.asset.meta
  Assets/Resources/Prefab/Item/Tentacle.prefab
  Assets/Resources/Prefab/Item/Tentacle.prefab.meta
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/AdrenalineSyringeEffect.cs
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/TentacleEffect.cs
  Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/TentacleEffect.cs.meta
  Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
Labels: 優先度中

#219 SEの実装
  Assets/Resources/Prefab/Enemy/TraceFeatureManager.prefab
  Assets/Resources/Prefab/Player.prefab
  Assets/Resources/Sound/SE/Enemy/se_blessing00.wav
  Assets/Resources/Sound/SE/Enemy/se_blessing00.wav.meta
  Assets/Resources/Sound/SE/Enemy/se_blessing01.wav
  Assets/Resources/Sound/SE/Enemy/se_blessing01.wav.meta
  Assets/Resources/Sound/SE/Player/FootSound.meta
  Assets/Resources/Sound/SE/Player/FootSound/RunFootSound.wav
  Assets/Resources/Sound/SE/Player/FootSound/RunFootSound.wav.meta
  Assets/Resources/Sound/SE/Player/FootSound/RunningFirstFoot.wav
  Assets/Resources/Sound/SE/Player/FootSound/RunningFirstFoot.wav.meta
  Assets/Resources/Sound/SE/Player/FootSound/RunningSecondFoot.wav
  Assets/Resources/Sound/SE/Player/FootSound/RunningSecondFoot.wav.meta
  Assets/Resources/Sound/SE/Player/FootSound/Sneak.wav
  Assets/Resources/Sound/SE/Player/FootSound/Sneak.wav.meta
  Assets/Resources/Sound/SE/Player/FootSound/WalkingFirstFoot.wav
  Assets/Resources/Sound/SE/Player/FootSound/WalkingFirstFoot.wav.meta
  Assets/Resources/Sound/SE/Player/FootSound/WalkingSecondFoot.wav
  Assets/Resources/Sound/SE/Player/FootSound/WalkingSecondFoot.wav.meta
  Assets/Resources/Sound/SE/Player/se_breathlessness00.wav
  Assets/Resources/Sound/SE/Player/se_breathlessness00.wav.meta
  Assets/Resources/Sound/SE/Player/se_casting00.wav
  Assets/Resources/Sound/SE/Player/se_casting00.wav.meta
  Assets/Scripts/Scenes/InGame/Enemy/EnemySoundManager.cs
  Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
  Assets/Scripts/Scenes/InGame/Player/Magic/PlayerMagic.cs
  Assets/Scripts/Scenes/InGame/Player/PlayerMove.cs
  Assets/Scripts/Scenes/InGame/Player/PlayerSoundManager.cs
Labels: 優先度低

#256 アイテム生成地点の修正とアイテムモデルの修正
  Assets/Plugins/Horror_House/Prefabs/Decals/Blood_Decals_09.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Armchair_01.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Faucet.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Kitchen_Module_01.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Kitchen_Module_02.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Kitchen_Module_04.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Kitchen_Stove.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Table_02.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Toilet_Cabinet.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Wardrobe_01.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Wardrobe_02.prefab
  Assets/Plugins/Horror_House/Prefabs/Furniture/Wardrobe_04.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Carpet_01.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Hand_Cream.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Black_Pepper.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Bread_01.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Canned_Plum.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Ladle_03.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Salt.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Soy_Sauce.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Teapot.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Kitchen/Toaster.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Ladle_Holder.prefab
  Assets/Resources/Prefab/Item/AdrenalineSyringe.prefab
  Assets/Resources/Prefab/Item/SanityPotion.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/2x2Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/2x3Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/2x3Room2_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/3x2Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/3x2Room2_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/3x3Room_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/3x3StairBottom_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/3x3StairTop_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/3x4Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/4x3Room2_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/4x4Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Lights/Bonfire.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Lights/Candle_06.prefab
  Assets/Resources/Prefab/Stage/escapeItemMarker.prefab
  Assets/Resources/Prefab/Stage/escapePoint.prefab
Labels: 優先度中

#252 リザルト画面の修正
  Assets/Resources/Prefab/ResultCanvas.prefab
  Assets/Scripts/Data/PlayerInformation.cs
  Assets/Scripts/Data/PlayerInformationFacade.cs
  Assets/Scripts/Scenes/InGame/Manager/EventManager.cs
  Assets/Scripts/Scenes/InGame/Manager/ResultManager.cs
  Assets/Scripts/Scenes/InGame/System/UI/ResultPresenter.cs
  Assets/Scripts/Scenes/InGame/System/UI/ResultView.cs
  Assets/Scripts/Scenes/InGame/System/UI/ResultView.cs.meta
Labels: 優先度中

#253 ジャーナルの未実装部分の実装
  Assets/Resources/Prefab/UI/Journal.meta
  Assets/Resources/Prefab/UI/Journal/JournalCanvas.prefab
  Assets/Resources/Prefab/UI/Journal/JournalCanvas.prefab.meta
  Assets/Resources/Prefab/UI/Journal/JournalPanel.prefab
  Assets/Resources/Prefab/UI/Journal/JournalPanel.prefab.meta
  Assets/Resources/Prefab/UI/Journal/JoutnalCells.prefab
  Assets/Resources/Prefab/UI/Journal/JoutnalCells.prefab.meta
  Assets/Resources/Prefab/UI/Journal/PlayerInput.prefab
  Assets/Resources/Prefab/UI/Journal/PlayerInput.prefab.meta
  Assets/Resources/Prefab/UI/JournalButton.prefab
  Assets/Resources/Prefab/UI/JournalButton.prefab.meta
  Assets/Scenes/JournalTest.unity
  Assets/Scripts/Scenes/InGame/Journal/JournalPageManager.cs
  Assets/Scripts/Scenes/InGame/Journal/JournalPresenter.cs
  Assets/Scripts/Scenes/InGame/Journal/View/CompatibilityView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/EnemyButtonView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/EnemyView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/FeatureView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/ItemView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/JournalView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/NameButtonView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/NameButtonView.cs.meta
  Assets/Scripts/Scenes/InGame/Journal/View/ProgressView.cs
  Assets/Scripts/Scenes/InGame/Journal/View/SpellView.cs
Labels: 優先度中

#257 プレイヤー情報にロビーで選択したアイテムと呪文を保存できるように修正
  Assets/Scripts/Data/PlayerInformation.cs
  Assets/Scripts/Data/PlayerInformationFacade.cs
Labels: 優先度高

#260 キャラクターの移動速度の修正
  Assets/Resources/Prefab/Enemy/DeepOnes.prefab
  Assets/Resources/Prefab/Enemy/MiGo.prefab
  Assets/Resources/Prefab/Enemy/SpawnOfCthulhu.prefab
  Assets/Scripts/Scenes/InGame/Multi/Player/MultiPlayerMove.cs
Labels: 優先度中
