Repository InnovaGameCreate/mythos-encounter, pull requests merged in 2024-09, with the labels that each got.

#168 深き者どもとクトゥルフの落とし子の仲間を呼ぶ能力に変更をくわえました
  Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
  Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
  Assets/Scripts/Scenes/InGame/Enemy/EnemyVisibilityMap.cs
  Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/DeepOnesAction.cs
  Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/SpawnOfCthulhuAction.cs
Labels: 優先度中

#177 ステージ生成の軽量化
  Assets/Resources/Materials/Marker.meta
  Assets/Resources/Materials/Marker/MarkerGreen.mat
  Assets/Resources/Materials/Marker/MarkerGreen.mat.meta
  Assets/Resources/Materials/Marker/MarkerRed.mat
  Assets/Resources/Materials/Marker/MarkerRed.mat.meta
  Assets/Resources/Materials/Marker/MarkerYellow.mat
  Assets/Resources/Materials/Marker/MarkerYellow.mat.meta
  Assets/Resources/Prefab/Stage.prefab
  Assets/Scenes/InGame_Stage.unity
  Assets/Scripts/Scenes/InGame/Stage/LinqRoomData.cs
  Assets/Scripts/Scenes/InGame/Stage/LinqRoomData.cs.meta
  Assets/Scripts/Scenes/InGame/Stage/RoomData.cs
  Assets/Scripts/Scenes/InGame/Stage/RoomLinqConfig.cs
  Assets/Scripts/Scenes/InGame/Stage/RoomLinqConfig.cs.meta
  Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
Labels: 優先度高

#179 VooDo人形にモデルを変更
  Assets/Resources/Prefab/Item/Doll.prefab
Labels: 優先度低

#193 ライトの設定変更および大幅な負荷軽減
  Assets/HDRPDefaultResources/DefaultSettingsVolumeProfile.asset
  Assets/HDRPDefaultResources/HDRenderPipelineGlobalSettings.asset
  Assets/Plugins/Horror_House/Prefabs/Furniture/Bedside_Table.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Ficus.prefab
  Assets/Plugins/Horror_House/Prefabs/Props/Home_Flower_03.prefab
  Assets/Resources/Prefab/Player.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/2x2Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/4x3Room1_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Lights/Chandelier_01.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Lights/Chandelier_03.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/EscapeRoom_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/Floor_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/InSideWallX_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/InSideWallY_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/OutSideWallX_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/OutSideWallY_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallXDoor_HH.prefab
  Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallYDoor_HH.prefab
  Assets/Scenes/Graphic/GraphicalTest/Sky and Fog Settings.asset
  Assets/Settings/HDRenderPipelineAsset.asset
  Assets/Settings/HDRenderPipelineGlobalSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: 優先度中

#194 アイテムのモデルのインポート
  Assets/Resources/Materials/Blood.mat
  Assets/Resources/Materials/Blood.mat.meta
  Assets/Resources/Materials/RedPaintCan.mat
  Assets/Resources/Materials/RedPaintCan.mat.meta
  Assets/Resources/Materials/adrenaline.mat
  Assets/Resources/Materials/adrenaline.mat.meta
  Assets/Resources/Materials/bandage.mat
  Assets/Resources/Materials/bandage.mat.meta
  Assets/Resources/Materials/flashlight.mat
  Assets/Resources/Materials/flashlight.mat.meta
  Assets/Resources/Materials/metal.mat
  Assets/Resources/Materials/metal.mat.meta
  Assets/Resources/Materials/socket.mat
  Assets/Resources/Materials/socket.mat.meta
  Assets/Resources/Materials/tentacle.mat
  Assets/Resources/Materials/tentacle.mat.meta
  Assets/Resources/Models.meta
  Assets/Resources/Models/Adrenaline.fbx
  Assets/Resources/Models/Adrenaline.fbx.meta
  Assets/Resources/Models/Bandage.fbx
  Assets/Resources/Models/Bandage.fbx.meta
  Assets/Resources/Models/BrainCan.fbx
  Assets/Resources/Models/BrainCan.fbx.meta
  Assets/Resources/Models/Flashlight.fbx
  Assets/Resources/Models/Flashlight.fbx.meta
  Assets/Resources/Models/RedPaintCan.fbx
  Assets/Resources/Models/RedPaintCan.fbx.meta
  Assets/Resources/Models/Tentacle.fbx
  Assets/Resources/Models/Tentacle.fbx.meta
  Assets/Resources/Prefab/Item/AdrenalineSyringe.prefab
  Assets/Resources/Prefab/Item/Bandage.prefab
  Assets/Resources/Prefab/Item/Doll.prefab
  Assets/Resources/Prefab/Item/HandLight.prefab
  Assets/Resources/Prefab/Stage/escapeItem.prefab
  Assets/Resources/Texture/Adrenaline.png
  Assets/Resources/Texture/Adrenaline.png.meta
  Assets/Resources/Texture/Bandage.png
  Assets/Resources/Texture/Bandage.png.meta
  Assets/Resources/Texture/BrainCan.png
  Assets/Resources/Texture/BrainCan.png.meta
  Assets/Resources/Texture/Flashlight.png
  Assets/Resources/Texture/Flashlight.png.meta
  Assets/Resources/Texture/RedPaintCan.png
  Assets/Resources/Texture/RedPaintCan.png.meta
  Assets/Resources/Texture/Tentacle.png
  Assets/Resources/Texture/Tentacle.png.meta
  Assets/Resources/Texture/blood.png
  Assets/Resources/Texture/blood.png.meta
Labels: 優先度低

#192 ホスト遷移の実装（完成版）
  Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion
  Assets/Scripts/HostMigration.meta
  Assets/Scripts/HostMigration/HostMigrationHandler.cs
  Assets/Scripts/HostMigration/HostMigrationHandler.cs.meta
  Assets/Scripts/HostMigration/HostMigrationObservable.cs
  Assets/Scripts/HostMigration/HostMigrationObservable.cs.meta
  Assets/Scripts/HostMigration/HostMigrationObserver.cs
  Assets/Scripts/HostMigration/HostMigrationObserver.cs.meta
  Assets/Scripts/HostMigration/Test.meta
  Assets/Scripts/HostMigration/Test/InGame.unity
  Assets/Scripts/HostMigration/Test/InGame.unity.meta
  Assets/Scripts/HostMigration/Test/Player.prefab
  Assets/Scripts/HostMigration/Test/Player.prefab.meta
  Assets/Scripts/HostMigration/Test/PlayerInfo.cs
  Assets/Scripts/HostMigration/Test/PlayerInfo.cs.meta
  Assets/Scripts/HostMigration/Test/Runner.prefab
  Assets/Scripts/HostMigration/Test/Runner.prefab.meta
  Assets/Scripts/HostMigration/Test/RunnerManager.cs
  Assets/Scripts/HostMigration/Test/RunnerManager.cs.meta
  Assets/Scripts/HostMigration/Test/Start.unity
  Assets/Scripts/HostMigration/Test/Start.unity.meta
  Assets/Scripts/HostMigration/Test/StartManager.cs
  Assets/Scripts/HostMigration/Test/StartManager.cs.meta
Labels: 優先度中

#199 リザルト画面の更新
  Assets/Resources/Prefab/Enemy/DeepOnes.prefab
  Assets/Resources/Prefab/Enemy/MiGo.prefab
  Assets/Resources/Prefab/Enemy/SpawnOfCthulhu.prefab
  Assets/Resources/Prefab/ResultCanvas.prefab
  Assets/Scenes/InGame.unity
  Assets/Scripts/Data/PlayerInformation.cs
  Assets/Scripts/Scenes/InGame/Enemy/EnemyStatus.cs
  Assets/Scripts/Scenes/InGame/Manager/EventManager.cs
  Assets/Scripts/Scenes/InGame/Manager/ResultManager.cs
Labels: 優先度中
